name: somesquares.org
markdown: kramdown
highlighter: pygments
permalink: /blog/:year/:i_month/:title
description: Wesley's blog
url: http://somesquares.org
collections:
    ghnm:
        relative_directory: ghnm2/



