name: somesquares.org
permalink: /blog/:year/:i_month/:title/
description: Wesley's blog
url: https://somesquares.org
collections:
    ghnm:
        relative_directory: ghnm2/

repository: wrbrooks/wrbrooks.github.io

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "master"

