name: Your New Jekyll Site
markdown: redcarpet
pygments: true
permalink: /blog/:year/:i_month/:title
description: Wesley's blog
url: http://jekyll.somesquares.org
redcarpet:
  extensions: ["lax_spacing"]
